name: fpm

on: [push, pull_request]

env:
  GFORTRAN_FLAGS: "-Wall -Wextra -Werror -pedantic -std=f2008 -ffree-line-length-none -fimplicit-none -pedantic"

jobs:
  fpm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install fpm
        uses: fortran-lang/setup-fpm@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check compiler
        run: gfortran --version

      - name: Check fpm
        run: fpm -v

      - name: Build & test the library
        run: |
            chmod +x ./run_test.sh
            ./run_test.sh
